
const IA_KEYS = { 
  ELEC_START: 'elec_start',
  ELEC_1: 'elec_1',
  ELEC_2: 'elec_2',
  ELEC_3: 'elec_3',
  CREA_END: 'crea_end',
  FOUILLE_1: 'fouille_1',
  FOUILLE_2: 'fouille_2',
  FOUILLE_3: 'fouille_3',
  GESTION_1: 'gestion_1',
  GESTION_2: 'gestion_2',
  GESTION_3: 'gestion_3',
  PENDERIE_1: 'penderie_1',
  PENDERIE_2: 'penderie_2',
  PENDERIE_3: 'penderie_3',
  AFFORDANCE_1: 'affordance_1',
  AFFORDANCE_2: 'affordance_2',
  AFFORDANCE_3: 'affordance_3',
  BASE_1: 'base_1',
  BASE_2: 'base_2',
  BASE_3: 'base_3',
  BASE_4: 'base_4',
  ORDI_CENTRAL_CLUE_1: 'ordi_central_1',
  ORDI_CENTRAL_CLUE_2: 'ordi_central_2',
  ORDI_CENTRAL_CLUE_3: 'ordi_central_3',
  ORDI_CENTRAL_END: 'ordi_central_end',
  KEYS_1: 'keys_1',
  KEYS_2: 'keys_2',
  KEYS_3: 'keys_3',
  WASON: 'wason',
  END: 'end',
}
const IA = {
  [IA_KEYS.ELEC_START]: {},
  [IA_KEYS.ELEC_1]: {},
  [IA_KEYS.ELEC_2]: {},
  [IA_KEYS.ELEC_3]: {},
  [IA_KEYS.CREA_END]: {},
  [IA_KEYS.FOUILLE_1]: {},
  [IA_KEYS.FOUILLE_2]: {},
  [IA_KEYS.FOUILLE_3]: {},
  [IA_KEYS.GESTION_1]: {},
  [IA_KEYS.GESTION_2]: {},
  [IA_KEYS.GESTION_3]: {},
  [IA_KEYS.PENDERIE_1]: {},
  [IA_KEYS.PENDERIE_2]: {},
  [IA_KEYS.PENDERIE_3]: {},
  [IA_KEYS.AFFORDANCE_1]: {},
  [IA_KEYS.AFFORDANCE_2]: {},
  [IA_KEYS.AFFORDANCE_3]: {},
  [IA_KEYS.BASE_1]: {},
  [IA_KEYS.BASE_2]: {},
  [IA_KEYS.BASE_3]: {},
  [IA_KEYS.BASE_4]: {},
  [IA_KEYS.ORDI_CENTRAL_CLUE_1]: {},
  [IA_KEYS.ORDI_CENTRAL_CLUE_2]: {},
  [IA_KEYS.ORDI_CENTRAL_CLUE_3]: {},
  [IA_KEYS.ORDI_CENTRAL_END]: {},
  [IA_KEYS.KEYS_1]: {},
  [IA_KEYS.KEYS_2]: {},
  [IA_KEYS.KEYS_3]: {},
  [IA_KEYS.WASON]: {},
  [IA_KEYS.END]: {},
}

module.exports {
ia
}
